### ISSUE TITLE
Numpy数组属性列表

### ISSUE THREAD

**Issue by doushizu** [LiuQixuan/PythonLearningNote#1]
你好，是两个很小很小的拼写问题。在Numpy数组属性列表中对应每个元素大小的应该是itemsize，表格里多加了一个s，打代码的时候会报错，对象的信息应该是flags，这里少打了一个s，也会报错。
即
ndarray.itemsize
not
ndarray.itemsizes

ndarray.flags
not
ndarray.flag

例子中用的都是对的，可见只是打错了一点。

**Comment by LiuQixuan** [comment]
首先，非常感谢你的反馈。
但是我暂时不能更新代码。因为目前没有再做更新的打算，这段时间正在忙其他事，预计9月份之后在做学习笔记，届时与大家分享。由于bug太小，更新后其他人会收到提示，但是发现并没有加入太多新内容会很失望，请谅解。
bug出现原因：我是用的是富文本编辑器，带有一定的自动完成功能，也愿我太懒，没有认真核对，直接tab就把一些函数名变量名打上去了，十分抱歉。今后会更加认真去做每一件事。
最后十分感谢你的支持，谢谢。
